/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedIntegrationRouteImport } from './routes/_authenticated/integration'
import { Route as AuthenticatedTriageIdRouteImport } from './routes/_authenticated/triage.$id'
import { Route as ApiPublicTriageIngestRouteImport } from './routes/api/public/triage/ingest'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIntegrationRoute =
  AuthenticatedIntegrationRouteImport.update({
    id: '/integration',
    path: '/integration',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTriageIdRoute = AuthenticatedTriageIdRouteImport.update({
  id: '/triage/$id',
  path: '/triage/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicTriageIngestRoute = ApiPublicTriageIngestRouteImport.update({
  id: '/api/public/triage/ingest',
  path: '/api/public/triage/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/triage/$id': typeof AuthenticatedTriageIdRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/integration': typeof AuthenticatedIntegrationRoute
  '/triage/$id': typeof AuthenticatedTriageIdRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/integration': typeof AuthenticatedIntegrationRoute
  '/_authenticated/triage/$id': typeof AuthenticatedTriageIdRoute
  '/api/public/triage/ingest': typeof ApiPublicTriageIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/auth' | '/integration' | '/triage/$id' | '/api/public/triage/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/auth' | '/integration' | '/triage/$id' | '/api/public/triage/ingest'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/integration'
    | '/_authenticated/triage/$id'
    | '/api/public/triage/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiPublicTriageIngestRoute: typeof ApiPublicTriageIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/integration': {
      id: '/_authenticated/integration'
      path: '/integration'
      fullPath: '/integration'
      preLoaderRoute: typeof AuthenticatedIntegrationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/triage/$id': {
      id: '/_authenticated/triage/$id'
      path: '/triage/$id'
      fullPath: '/triage/$id'
      preLoaderRoute: typeof AuthenticatedTriageIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/triage/ingest': {
      id: '/api/public/triage/ingest'
      path: '/api/public/triage/ingest'
      fullPath: '/api/public/triage/ingest'
      preLoaderRoute: typeof ApiPublicTriageIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedIntegrationRoute: typeof AuthenticatedIntegrationRoute
  AuthenticatedTriageIdRoute: typeof AuthenticatedTriageIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedIntegrationRoute: AuthenticatedIntegrationRoute,
  AuthenticatedTriageIdRoute: AuthenticatedTriageIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiPublicTriageIngestRoute: ApiPublicTriageIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
